# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "An Do's Blog"
title_separator          : "-"
subtitle                 : "HUST Student"
name                     : "An Do"
description              : "The work of a programmer is to change the world, make it better ❤️"
url                      : "sweet-blogs.github.io"
baseurl                  : "/"
repository               : "sweet-blogs/sweet-blogs.github.io"
teaser                   : "/assets/images/logo.jpeg"
logo                     : # "/assets/images/logo.jpeg"
masthead_title           : "An Do's Blog"

breadcrumbs              : true  # disabled by default

words_per_minute         : 200
comments:
  provider               : "facebook" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                : # 
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "master"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "docs/_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xm
  hide                   : # true, false (default)

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : algolia # lunr (default), algolia, google

algolia:
  application_id         : "ZFKVMGN4NP" # YOUR_APPLICATION_ID
  index_name             : "ando_blogs" # YOUR_INDEX_NAME
  search_only_api_key    : "fc823eb496b57fd7216fecf6b7ee6500" # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : true # true (default), false

google:
  search_engine_id       : "e7e06be410d4fa76c" # YOUR_SEARCH_ENGINE_ID
  instant_search         : true # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : "_sweetttt_"
facebook:
  username               : "An Do"
  app_id                 : # A Facebook app ID
  publisher              : # A Facebook page URL or ID of the publishing entity
og_image                 : "/assets/images/logo.jpeg"
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "An Do"
  avatar           : "/assets/images/bio-photo.jpeg"
  bio              : "I am a Computer Science student from Viet Nam"
  location         : "Ha Noi, Viet Nam"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "andoDsAI@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "andoDsAI.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/_sweetttt_"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/andoDsAI"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/andoDsAI"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/_sweettt.__"

# Site Footer
footer:
  links:
    - label: "Email"
      icon : "fab fa-fw fa-google"
      url  : "andoDsAI@gmail.com"
    - label: "Twitter"
      icon : "fab fa-fw fa-twitter-square"
      url  : "https://twitter.com/_sweetttt_"
    - label: "Facebook"
      icon : "fab fa-fw fa-facebook-square"
      url  : "https://facebook.com/andoDsAI"
    - label: "GitHub"
      icon : "fab fa-fw fa-github"
      url  : "https://github.com/andoDsAI"
    - label: "GitLab"
      icon : "fab fa-fw fa-gitlab"
      url  : "https://gitlab.com/andoDsAI"
    - label: "LinkedIn"
      icon : "fab fa-fw fa-linkedin-in"
      url  : "https://www.linkedin.com/in/andoDsAI"
    - label: "Instagram"
      icon : "fab fa-fw fa-instagram"
      url  : "https://www.instagram.com/_sweettt.__"
    - label: "Buy me a coffee"
      icon : "fas fa-coffee"
      url  : "https://www.buymeacoffee.com/andoDsAI"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Bangkok


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives
  # - jekyll-github-metadata

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-archives


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: archive
    tag: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: true
      share: true
  # _pets
  - scope:
      path: ""
      type: pets
    values:
      layout: single
      author_profile: true
      share: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
